### PR TITLE
#issue 23 Improved UI

### PR DESCRIPTION
**Pull request by kairveeehh**
fixed the needed UI with bordersw , hovering features and visually appealing 
hovering for one card is shown -- not an error 
## #23 improve UI
Screenshot 2024-05-10 112612
Screenshot 2024-05-10 112602

### CODE REVIEW

**Comment by kairveeehh** [comment]
@Mayank2808sharma can you please merge my PRs as well?

**Comment by Mayank2808sharma** [comment]
Hey @kairveeehh 
The blue border does not look good.
maybe you can see other websites or products for the idea.

**Comment by kairveeehh** [comment]
> Hey @kairveeehh The blue border does not look good. maybe you can see other websites or products for the idea.

@Mayank2808sharma SURE  will change and update it and send you again

**Comment by kairveeehh** [comment]
@Mayank2808sharma  do you have any specific recommendation for the UI , cause I am a bit confused
your help would be beneficial :)

**Comment by kairveeehh** [comment]
I have closed this one , will add a new one as there were some local repo issues with this fork of mine , sorry 
@Mayank2808sharma

**Pull request closed without merging**
