### PR TITLE
Replaced the Twitter logo to X

### PR DESCRIPTION
**Pull request by codercake**
What is the purpose of this pull request?
- It replaces the outdated Twitter logo with the new one.

Reference Screenshot:
image

### CODE REVIEW

**Comment by codercake** [comment]
Added for #89. Merge it under the **GSSoC'24** and **Level 3** Labels.

**Comment by codercake** [comment]
@ENZOMOTIVE @Mayank2808sharma Can you review my PR please?

**Comment by ENZOMOTIVE** [comment]
I am not admin . I am a contributor too.

**Comment by Mayank2808sharma** [comment]
please create an issue first

**Comment by codercake** [comment]
the issue has been created already. #88 
kindly review the pr and add the labels gssoc, label 3. thank you.

**Comment by codercake** [comment]
@Mayank2808sharma 
Have you reviewed the PR yet?

**Pull request closed without merging**
